helm/templates/deployment.yaml, helm/templates/service.yaml, helm/values.yaml, server/services/connection-service.js, server/services/message-service.js
https://eaflood.atlassian.net/browse/FPD-395
Service was able to connect to message queue without modification, however have made changes to error handling and Helm chart to increase stability.
=> Update payment service to ensure connectivity to Azure Service Bus

README.md, azure-pipelines.yaml, docker-compose.local.yaml, docker-compose.override.yaml, docker-compose.test.yaml, docker-compose.yaml, helm/production-values.yaml, helm/values.yaml, package.json, scripts/deploy, scripts/start, scripts/start-isolated, scripts/stop, scripts/test, server/config/config.js, server/routes/home.js, test/server/routes/home.test.js
Rename "mine-support" to "FFC Demo".
https://eaflood.atlassian.net/browse/FPD-526
https://eaflood.atlassian.net/browse/FPD-533
https://eaflood.atlassian.net/browse/FPD-519
https://eaflood.atlassian.net/browse/FPD-513
=> Rename Core Values

README.md, scripts/connected-start, scripts/connected-stop, scripts/start, scripts/stop
https://eaflood.atlassian.net/browse/FPD-480
Default to isolated start/stop and provide additional scripts for
running this service alongside others in the Mine Support stack.
=> Clarify start/stop scripts

README.md
https://eaflood.atlassian.net/browse/FPD-505
=> Build badge updated

Jenkinsfile, helm/ffc-demo-payment-service/jenkins-aws.yaml, helm/ffc-demo-payment-service/templates/deployment.yaml
https://eaflood.atlassian.net/browse/PSD-179
=> Add Jenkins build pipeline

Jenkinsfile, docker-compose.link.yaml, docker-compose.override.yaml, docker-compose.test.yaml, docker-compose.yaml, package.json, scripts/test
https://eaflood.atlassian.net/browse/PSD-196
Use docker compose projects to isolate tests
Fix bug where tests were waiting for a service that was not available
=> Isolate tests from host environment

Jenkinsfile
https://eaflood.atlassian.net/browse/PSD-231
Use a unique value for the redeployOnChange annotation to trigger pod
redeployment in Kubernetes on each deployment from the Jenkins build
pipeline.
=> Roll pods on every deployment from build pipeline

package-lock.json, server/migrations/20190807095529-transfer-value-to-payments.js
https://eaflood.atlassian.net/browse/PSD-1
=> Fix migration which does not retain data

Jenkinsfile, helm/ffc-demo-payment-service/templates/deployment.yaml, helm/ffc-demo-payment-service/templates/service.yaml
https://eaflood.atlassian.net/browse/PSD-315
=> Quoted all values as per Helm best practice advice

Jenkinsfile
https://eaflood.atlassian.net/browse/PSD-413
=> demo payment service should analyse code

README.md
https://eaflood.atlassian.net/browse/PSD-418
=> Remove ADO badge

Jenkinsfile, jest.config.js
https://eaflood.atlassian.net/browse/PSD-427
=> Update Jenkinsfiles to report code coverage to SonarQube 

Dockerfile, Jenkinsfile, docker-compose.link.yaml, docker-compose.override.yaml, docker-compose.test.yaml, docker-compose.yaml, helm/ffc-demo-payment-service/jenkins-aws.yaml, helm/ffc-demo-payment-service/values.yaml, package-lock.json, package.json
https://eaflood.atlassian.net/browse/PSD-384
Extend the FFC Node parent image and use multi-stage builds to efficiently produce minimal production images
and feature-full development/test images from a single build.
=> Use Defra parent image

Jenkinsfile, docker-compose.yaml, package.json
https://eaflood.atlassian.net/browse/PSD-539
=> Update pipeline to support Non Production

Jenkinsfile, package.json
https://eaflood.atlassian.net/browse/PSD-504
=> Services should be isolated by folder in Jenkins

Jenkinsfile, helm/ffc-demo-payment-service/templates/deployment.yaml, helm/ffc-demo-payment-service/templates/labels.yaml, helm/ffc-demo-payment-service/templates/service.yaml, helm/ffc-demo-payment-service/values.yaml, package.json
https://eaflood.atlassian.net/browse/PSD-530
=> PSD 530 k8s labels

package.json, sonar-project.properties
https://eaflood.atlassian.net/browse/PSD-860
=> Use SonarCloud CI

README.md, docker-compose.yaml, helm/ffc-demo-payment-service/deployment-config-keys.txt, helm/ffc-demo-payment-service/templates/config-map.yaml, helm/ffc-demo-payment-service/values.yaml, index.js, package-lock.json, package.json, server/services/app-insights.js
https://eaflood.atlassian.net/browse/PSD-821
Add app insights to investigate the metrics captured.
=> Integrate app insights

README.md, docker-compose.yaml, helm/ffc-demo-payment-service/templates/config-map.yaml, helm/ffc-demo-payment-service/templates/container-secret.yaml, helm/ffc-demo-payment-service/values.yaml, package.json
https://eaflood.atlassian.net/browse/PSD-821
=> Make App Insights configuration consistent

Jenkinsfile, package.json
https://eaflood.atlassian.net/browse/PSD-867
=> use version 8 of library

helm/ffc-demo-payment-service/templates/developer-rolebinding.yaml, package.json
https://eaflood.atlassian.net/browse/PSD-692
=> Rolebinding only on PR deployment

.snyk, package.json, provision.azure.yaml
https://eaflood.atlassian.net/browse/PSD-929
=> Add Azure manifest

Jenkinsfile, helm/ffc-demo-payment-service/templates/config-map.yaml, helm/ffc-demo-payment-service/values.yaml, package.json, scripts/migration/database-down, scripts/migration/database-up
https://eaflood.atlassian.net/browse/PSD-948
=> Allow postgres schema to be set

changelog/db.changelog-1.0.xml, package.json, scripts/migration/database-down
https://eaflood.atlassian.net/browse/PSD-965
=> Psd 965 add liquibase version

.secrets.baseline, README.md, docker-compose.yaml, jest.config.js, package-lock.json, package.json, server/services/messaging/message-base.js, server/services/messaging/message-receiver.js, test/contract/ffc-demo-payment-service.test.js, test/db-helper.js, test/integration/local/services/message-receiver.test.js
https://eaflood.atlassian.net/browse/PSD-956
=> Run all tests

Dockerfile, package-lock.json, package.json
https://eaflood.atlassian.net/browse/PSD-1009
=> Update parent image to one with CA cert

docker-compose.yaml, package-lock.json, package.json
https://eaflood.atlassian.net/browse/PSD-923
=> Enable App Insights key to be set locally

.snyk, package-lock.json, package.json
https://eaflood.atlassian.net/browse/PSD-978
=> Remove unnecessary snyk ignores

package-lock.json, package.json, server/services/app-insights.js
https://eaflood.atlassian.net/browse/PSD-924
=> Log when App Insights is active

.snyk, changelog/db.changelog-1.0.xml, package-lock.json, package.json, server/services/app-insights.js
https://eaflood.atlassian.net/browse/PSD-1012
=> Psd 1012 update rollback tags

app/plugins/logging.js, app/plugins/process-error-response.js, app/schedule/index.js, docker-compose.migrate.yaml, package-lock.json, package.json
This pr includes the below changes to update dependent packages to the latest version
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/231573
=> 231573: Updating dependency packages

.azuredevops/build.yaml, app/config/database-config.js, helm/ffc-demo-payment-service/Chart.yaml, helm/ffc-demo-payment-service/templates/_container.yaml, helm/ffc-demo-payment-service/templates/cluster-ip-service.yaml, helm/ffc-demo-payment-service/templates/config-map.yaml, helm/ffc-demo-payment-service/templates/container-secret.yaml, helm/ffc-demo-payment-service/templates/deployment.yaml, helm/ffc-demo-payment-service/templates/developer-rolebinding.yaml, helm/ffc-demo-payment-service/values.yaml, package-lock.json, package.json
This pr includes the changes to update helm charts for ADP and added ADO build pipeline.
https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/231730
=> 231730: Updated helm charts for ADP and added ADO build pipeline

db-migration.Dockerfile, package-lock.json, package.json, scripts/migration/database-up
This PR contains the changes to Retrieve Access Token for DB Migrations using Workload Identity
[AB#260861](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/260861)
=> 260861: Retrieve Access Token for DB Migrations using Workload Identity

app/services/database-service.js, package-lock.json, package.json, test/unit/config/constants.test.js, test/unit/config/database-config.test.js, test/unit/config/event-config.test.js, test/unit/config/index.test.js, test/unit/config/mq-config.test.js, test/unit/events/create-event.test.js, test/unit/events/index.test.js, test/unit/index.test.js, test/unit/messaging/index.test.js, test/unit/messaging/process-payment-message.test.js, test/unit/messaging/process-schedule-message.test.js, test/unit/models/payment.test.js, test/unit/models/schedule.test.js, test/unit/payment/index.test.js, test/unit/plugins/error-pages.test.js, test/unit/plugins/logging.test.js, test/unit/plugins/router.test.js, test/unit/routes/healthy.test.js, test/unit/routes/healthz.test.js, test/unit/routes/schedule.test.js, test/unit/schedule/index.test.js, test/unit/services/app-insights.test.js, test/unit/services/database-service.test.js
This PR contains the fixes to increase code coverage to >90%
[AB#282429](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/282429)
=> 282429: Code coverage fix to >90%

helm/ffc-demo-payment-service/values.yaml, package-lock.json, package.json
Removed duplicate values defined in the values.yaml files.   Also removed values which are the same as the defaults in the helm-library.
Information defined in the app config files will not be duplicated in the values.yaml file
Tested changes against SND1 Cluster and Demo Apps are still working successfully.
=> 277457: Remove duplicate values defined in the values.yaml files for each repo

README.md, helm/ffc-demo-payment-service/values.yaml, package-lock.json, package.json
Helm cleanup and Readme updates
=> Helm cleanup and Readme updates

.azuredevops/build.yaml, package.json
*A brief description of changes being made*
*Link to the relevant work items: 
[AB#323021](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/323021)
Simplify the variable import from variable groups specific to environment
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=498700&view=results
Have you updated any related templates, repositories or dependencies for new changes? We must ensure any dependencies like Software Templates are updated to include the latest changes to be scaffolded for all services where applicable.
=> 323021: Variable Import 

appConfig/appConfig.yaml, helm/ffc-demo-payment-service-infra/Chart.yaml, package.json
Changes related to change for topicsubscription naming convention in ASO helm library
Related PR:
https://github.com/DEFRA/adp-aso-helm-library/pull/27
Relates to ADO Work Item [AB#337727](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/337727)
Tested CI build for 'ffc-demo-payment-service'
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=500227&view=results
=> 337727: TopicSubscription Name updated 

docker-compose.link.yaml, docker-compose.migrate.yaml, docker-compose.override.yaml, docker-compose.test.debug.yaml, docker-compose.test.watch.yaml, docker-compose.test.yaml, docker-compose.yaml, package-lock.json, package.json
Updated to use postgres 15 image
[AB#309469](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/309469)
=> 309469: Update to use postgres 15 image

appConfig/appConfig.dev1.yaml, appConfig/appConfig.prd1.yaml, appConfig/appConfig.pre1.yaml, appConfig/appConfig.snd1.yaml, appConfig/appConfig.snd2.yaml, appConfig/appConfig.snd3.yaml, appConfig/appConfig.tst1.yaml, appConfig/appConfig.yaml, package.json
I have taken out the POSTGRES_DB key & value from the common appconfig and have added it individually within the different environments. snd1 and snd2 has the value of 'fcp-demo-payment' whilst the others have the value of 'ffc-demo-payment'
[ AB#372180](https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/372180/)
=> Updated postgres_db value

.azuredevops/build.yaml, package.json
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*
=> Include Platform Envs

.azuredevops/build.yaml, db-migration.Dockerfile, package.json
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*
=> db migration base image

appConfig/appConfig.dev1.yaml, appConfig/appConfig.prd1.yaml, appConfig/appConfig.pre1.yaml, appConfig/appConfig.snd3.yaml, appConfig/appConfig.snd4.yaml, appConfig/appConfig.tst1.yaml
*A brief description of changes being made*
*Link to the relevant work items: e.g: Relates to ADO Work Item [AB#213700](https://dev.azure.com/defragovuk/93c65135-d16b-49d6-a191-4a5313532779/_workitems/edit/213700) and builds on #3376 (link to ADO Build ID URL)*
=> Add SND4 Config
